config/routes.rb
Rails.application.routes.draw do
  get '/privacy', to: 'pages#privacy'
  get '/contact', to: 'pages#contact'
  get '/about', to: 'pages#about'
  root to: 'pages#index'
  get 'pages/index'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/privacy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources 'feedbacks', only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback
  include ActiveModel::Model
  attr_accessor :full_name, :email, :topic, :comment
  validates :topic, :comment, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "only allows valid emails" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :create_feedback

  private
  def create_feedback
    @feedback = Feedback.new
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  def create
   @feedback = Feedback.new feedback_params

   if @feedback.valid?
     FeedbackMailer.send_feedback(@feedback).deliver_now
     redirect_back(fallback_location: root_path, notice: "feedback received, thanks!")
   else
     redirect_back(fallback_location: root_path, notice: "There was an issue with your submission!")
   end
  end

  private

  def feedback_params
   params.require(:feedback).permit(:full_name, :email, :topic, :comment)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def privacy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
def bootstrap_class_for flash_type
  { success: "alert-success", error: "alert-error", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
end

def flash_messages(opts = {})
  flash.each do |msg_type, message|
    concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
      concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
    end)
  end
  nil
end

  def site_name
    @site_name = nil
    @site_name = @site_name || Rails.application.class.parent_name.titleize
  end

  def flash_class(level)
    case level
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-error"
    when :alert then "alert alert-error"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/feedback/RAILS_ENV=development.html.haml
%h1= class_name + "#" + @action

%p
  = @greeting + ", find me in app/views/feedback/RAILS_ENV=development.html.haml"

app/views/feedback/RAILS_ENV=development.text.haml
Feedback#RAILS_ENV=development

= @greeting + ", find me in app/views/feedback/RAILS_ENV=development.text.haml"

app/views/feedback/_feedback.html.haml
/ Button trigger modal
%button.btn.btn-primary{"data-target" => "#contact-mailer--modal", "data-toggle" => "modal", :type => "button"}
  Feedback
/ Modal
#contact-mailer--modal.modal.fade.bd-example-modal-md{"aria-hidden" => "true", "aria-labelledby" => "contact-mailer--modalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-md{:role => "document"}
    .modal-content
      .modal-header
        %h4.modal-title Submit Your Feedback
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = form_with model: @feedback do |f|
          .form-group
            = notice
            = @feedback.errors.full_messages.join(', ')
          .form-group
            = f.label :full_name, 'Full name', :class => "control-label"
            #form_div
              = f.text_field :full_name, placeholder: 'Full Name'
          .form-group
            = f.label :email, 'eMail', :class => "control-label"
            #form_div
              = f.email_field :email, placeholder: 'email@somewhere.com', required: true
          .form-group
            = f.label :topic, 'Topic', :class => "control-label"
            #form_div
              = f.select(:topic, options_for_select([['I have some feedback...','feedback'],['I have a question...', 'question'],['I have a feature request...','feature'],['I’d like to report a bug...','bug'],['Other','other']],1))
          .form-group
            = f.label :comment, 'Comment', :class => "control-label"
            #form_div
              = f.text_area :comment, placeholder: 'Comment', required: true
          .form-group
            #form_div
              = f.submit :submit, :class => "btn btn-success"

app/views/layouts/_flash_messages.html.haml
%div
  - flash.each do |key, value|
    %div{:class => "#{flash_class(key)} fade in"}
      %a.close{"data-dismiss" => "alert", :href => "#"} ×
      = value

app/views/layouts/_footer.html.haml
%footer.fixed-bottom.bg-dark
  .d-flex.flex-row.justify-content-between.align-items-center
    .footer-logo
      -# = link_to image_tag("#{site_name}Logo.png", class: 'navbar-brand navbar-logo', alt: "#{site_name} Logo, link to home page."), root_path
      = link_to site_name, root_path, class:'navbar-brand'
    .footer-links
      %ul.navbar-nav.flex-row.justify-content-around
        %li.nav-item= link_to 'About', about_path, class:'nav-link'
        %li.nav-item= link_to 'Contact Us', contact_path, class:'nav-link'
        %li.nav-item= link_to 'Privacy Policy', privacy_path, class:'nav-link'
      .footer-copyright.text-center
        = link_to "© 2018 - Copyright #{site_name}, All Rights Reserved", about_path
    .footer-contact
    = render 'feedback/feedback'

app/views/layouts/_header.html.haml
%header
  / Navigation
  %nav#mainNav.navbar.fixed-top.navbar-expand-md.navbar-dark.bg-dark.mb-4
    %button.navbar-toggler{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarCollapse.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto.text-uppercase
        %li.nav-item
          = link_to site_name, root_path, class: 'navbar-brand', id: root_path(anchor: 'page-top')
          %span.sr-only (current)

      .nav.my-2.my-md-0
        %ul.navbar-nav.text-uppercase.ml-auto
          %li.nav-item= link_to "About", about_path, class:"nav-link"
          %li.nav-item= link_to "Contact Us", contact_path, class:"nav-link"
          %li.nav-item= link_to "Privacy", privacy_path, class:"nav-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Minitable
    = csrf_meta_tags
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body#page-top{:class => controller.controller_name}
    .corner-ribbon.top-right.sticky.red.shadow Work in Progress
    = debug(params) if Rails.env.development?
    = render 'layouts/header'
    .content#content
      = yield
      = render 'layouts/footer'
      = render 'feedback/feedback'

app/views/pages/about.html.haml
%h1 Pages#about
%p Find me in app/views/pages/about.html.haml

app/views/pages/contact.html.haml
%h1 Pages#contact
%p Find me in app/views/pages/contact.html.haml

.container.text-center.contact-us--form
  %h1 Pages#contact
  %p Find me in app/views/pages/contact.html.haml
  %h3.heading-style-1.text-center.text-uppercase.text-weight-normal
    Contact Us
  = form_with model: @feedback, class: 'contact-us-page--form' do |f|

    .form-group
      = notice
      = @feedback.errors.full_messages.join(', ')

    .form-group
      = f.text_field :full_name, placeholder: 'Full Name'

    .form-group
      = f.email_field :email, placeholder: 'email@somewhere.com', required: true

    .form-group
      = f.label :topic, 'Topic', :class => "control-label"
      = f.select(:topic, options_for_select([['I have some feedback...','feedback'],['I have a question...', 'question'],['I have a feature request...','feature'],['I’d like to report a bug...','bug'],['Other','other']],1))

    .form-group
      = f.text_area :comment, placeholder: 'What is on your mind?', required: true

    .form-group
      = f.submit :submit, :class => "btn btn-success"

app/views/pages/index.html.haml
%h1 Pages#index
%p Find me in app/views/pages/index.html.haml

app/views/pages/privacy.html.haml
%h1 Pages#privacy
%p Find me in app/views/pages/privacy.html.haml